[variables]
NIXPACKS_NODE_VERSION="20"
NIXPACKS_NO_CACHE="1"

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install --global yarn", "yarn install"]

[phases.build]
cmds = ["npx expo export --platform web"]

[start]
cmd = "npx serve -s dist -l 3002"
