[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install -g corepack", "yarn install"]

[phases.build]
cmds = ["npx expo export --platform web"]

[start]
cmd = "npx serve -s dist -l 3002"
